#!/usr/bin/env bash
# Copyright (C) 2026 Javad Rajabzadeh
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# The ABI 1 stability gate.
#
# include/hydra.h describes a binary layout that third parties have already
# compiled into their own programs. Once a struct field has an offset, that
# offset is the ABI: moving it, widening it, or renumbering an enumerator is a
# break that compiles cleanly, links cleanly, and hands somebody the wrong
# bytes at run time. `make header-check` catches a header that drifted from the
# Rust; it says nothing about whether the change was ALLOWED.
#
# This script is the half that answers that. crates/hydra-ffi/abi/abi-1.manifest
# is the frozen layout of ABI 1 - every enumerator's value, every field's offset
# and width, every struct's size, every exported symbol. The rules in
# docs/ffi/ABI.md are enforced against it here:
#
#   enumerators   never change value, never disappear; new ones may be appended
#   fields        never move, never change width, never disappear
#   structs       size is frozen, EXCEPT the two size-prefixed configuration
#                 structs, which may grow at the end
#   symbols       never disappear
#
#   scripts/ffi-abi-compat.sh                 check the working tree
#   scripts/ffi-abi-compat.sh --header PATH   check some other header
#   scripts/ffi-abi-compat.sh --lib PATH      also check symbols in that archive
#   scripts/ffi-abi-compat.sh --update        rewrite the baseline
#
# --update is for two occasions only: appending to ABI 1 in a way the rules
# above permit, and starting a new ABI version. It is never the way to make a
# failure go away.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
header="$root/include/hydra.h"
baseline="$root/crates/hydra-ffi/abi/abi-1.manifest"
out="$root/target/ffi-abi-compat"
lib=""
update=0

while [ $# -gt 0 ]; do
    case "$1" in
        --header) header="$2"; shift 2 ;;
        --baseline) baseline="$2"; shift 2 ;;
        --lib) lib="$2"; shift 2 ;;
        --update) update=1; shift ;;
        -h|--help) sed -n '3,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "error: unknown argument $1" >&2; exit 2 ;;
    esac
done

[ -f "$header" ] || { echo "error: no such header: $header" >&2; exit 2; }
mkdir -p "$out/include"

# Staged under its canonical name, so that `--header` can be pointed at a copy
# extracted from a git tag - which has a tag-shaped filename - and the probe's
# `#include "hydra.h"` still resolves.
cp "$header" "$out/include/hydra.h"

# --------------------------------------------------------------------------
# 1. Turn the header into a program that reports its own layout.
#
# Generated from the header rather than hand-written, because a hand-written
# probe is a third list of field names to keep in step with the other two, and
# the field it forgets is the field that moves.
# --------------------------------------------------------------------------
probe="$out/abi_manifest.c"

awk '
function flush_struct(name,   i) {
    if (name == "") return
    printf "    printf(\"struct %s %%lu\\n\", (unsigned long)sizeof(%s));\n", name, name
    for (i = 1; i <= nfields; i++) {
        printf "    printf(\"field %s.%s %%lu %%lu\\n\",\n", name, fields[i]
        printf "           (unsigned long)offsetof(%s, %s),\n", name, fields[i]
        printf "           (unsigned long)sizeof(((%s *)0)->%s));\n", name, fields[i]
    }
    nfields = 0
}
BEGIN {
    print "/* GENERATED by scripts/ffi-abi-compat.sh - do not edit, do not commit. */"
    print "#include <stddef.h>"
    print "#include <stdio.h>"
    print "#include \"hydra.h\""
    print ""
    print "int main(void)"
    print "{"
    print "    printf(\"abi %lu\\n\", (unsigned long)HYDRA_FFI_ABI_VERSION);"
    depth = 0; nfields = 0; in_struct = 0; enum_name = ""
}
# An enum body: the tag line, then enumerators until the closing brace.
/^enum hydra_[a-z_]+_t$/ { enum_name = $2; next }
enum_name != "" && /^  HYDRA_[A-Z0-9_]+ = / {
    name = $1
    printf "    printf(\"enum %s.%s %%ld\\n\", (long)%s);\n", enum_name, name, name
    next
}
enum_name != "" && /^};/ { enum_name = ""; next }
enum_name != "" { next }
# An anonymous struct typedef. cbindgen emits every ABI struct this way; the
# opaque handle is `typedef struct hydra_engine_t hydra_engine_t;` and has no
# body, so it never matches here.
/^typedef struct \{/ { in_struct = 1; depth = 1; nfields = 0; next }
in_struct && /^\} hydra_[a-z0-9_]+_t;/ {
    name = $2; sub(/;$/, "", name)
    flush_struct(name)
    in_struct = 0; depth = 0
    next
}
in_struct {
    line = $0
    sub(/\/\*.*/, "", line)          # doc comment opener
    if (line ~ /^[ \t]*\*/) next     # doc comment continuation
    gsub(/^[ \t]+|[ \t]+$/, "", line)
    if (line == "") next
    if (line !~ /;$/) next
    # `uint8_t reserved[32];` and `const char *const *urls;` alike: the field
    # name is the last identifier before the semicolon or the array bound.
    field = line
    sub(/;$/, "", field)
    sub(/\[.*$/, "", field)
    gsub(/[ \t]+$/, "", field)
    n = split(field, parts, /[ \t*]+/)
    fields[++nfields] = parts[n]
    next
}
END {
    print "    return 0;"
    print "}"
}
' "$header" > "$probe"

# --------------------------------------------------------------------------
# 2. Compile and run it. Nothing here links against libhydra: sizeof and
#    offsetof are answered by the header alone, which is what lets this run on
#    a machine that has not built the library at all.
# --------------------------------------------------------------------------
host="$(rustc -vV 2>/dev/null | sed -n 's/^host: //p' || true)"
case "$host" in
    *-pc-windows-msvc) toolchain="msvc" ;;
    *)                 toolchain="unix" ;;
esac

include_dir="$out/include"
current="$out/current.manifest"

if [ "$toolchain" = msvc ]; then
    export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'
    winpath() { if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi; }
    CC="${CC:-cl}"
    command -v "$CC" >/dev/null 2>&1 || {
        echo "error: $CC is not on PATH - run this from a Visual Studio developer shell" >&2
        exit 1
    }
    rsp="$out/probe.rsp"
    {
        printf -- '/nologo\n/W3\n/WX\n/std:c11\n/D_CRT_SECURE_NO_WARNINGS\n'
        printf -- '/I"%s"\n' "$(winpath "$include_dir")"
        printf -- '/Fe:"%s"\n' "$(winpath "$out/abi_manifest.exe")"
        printf -- '/Fo:"%s"\n' "$(winpath "$out/abi_manifest.obj")"
        printf '"%s"\n' "$(winpath "$probe")"
    } > "$rsp"
    "$CC" "@$(winpath "$rsp")" >/dev/null
    "$out/abi_manifest.exe" > "$current"
else
    CC="${CC:-cc}"
    "$CC" -std=c11 -Wall -Wextra -Wpedantic -Werror -I "$include_dir" \
        -o "$out/abi_manifest" "$probe"
    "$out/abi_manifest" > "$current"
fi

# --------------------------------------------------------------------------
# 3. The symbols the header promises. A declaration that no longer has a
#    definition behind it is an ABI break that the layout check cannot see.
# --------------------------------------------------------------------------
grep -A1 '^HYDRA_API$' "$header" \
    | grep -o 'hydra_[a-z0-9_]*(' \
    | sed 's/($//;s/(//' \
    | sort -u \
    | sed 's/^/symbol /' >> "$current"

LC_ALL=C sort -o "$current" "$current"

if [ "$update" = 1 ]; then
    cp "$current" "$baseline"
    echo "wrote $baseline"
    echo
    echo "Do this only to APPEND to ABI 1 within the rules, or to start a new"
    echo "ABI version. Read docs/ffi/ABI.md before you commit it."
    exit 0
fi

[ -f "$baseline" ] || {
    echo "error: no baseline at $baseline; create it with --update" >&2
    exit 2
}

# --------------------------------------------------------------------------
# 4. Compare, under the ABI 1 rules rather than by diffing.
#
# A plain diff would reject an addition the contract explicitly allows, and
# then nobody could ever append a field. The asymmetry is the whole point:
# everything in the baseline must still be true, and the current header may
# say more.
# --------------------------------------------------------------------------
awk -v baseline="$baseline" -v current="$current" '
function fail(msg) { print "  BREAK  " msg; breaks++ }
BEGIN {
    # The only two structs a caller allocates and hands to hydra with its own
    # size in a leading field. That size prefix is what lets the library write
    # only as many bytes as the caller`s header declared, and it is the only
    # reason these two may grow.
    growable["hydra_engine_config_t"] = 1
    growable["hydra_job_config_t"] = 1

    while ((getline line < baseline) > 0) {
        n = split(line, f, " ")
        if (f[1] == "abi")         base_abi = f[2]
        else if (f[1] == "enum")   base_enum[f[2]] = f[3]
        else if (f[1] == "field")  { base_off[f[2]] = f[3]; base_width[f[2]] = f[4] }
        else if (f[1] == "struct") base_size[f[2]] = f[3]
        else if (f[1] == "symbol") base_sym[f[2]] = 1
    }
    while ((getline line < current) > 0) {
        n = split(line, f, " ")
        if (f[1] == "abi")         cur_abi = f[2]
        else if (f[1] == "enum")   { cur_enum[f[2]] = f[3]; seen_enum[f[2]] = 1 }
        else if (f[1] == "field")  { cur_off[f[2]] = f[3]; cur_width[f[2]] = f[4]; seen_field[f[2]] = 1 }
        else if (f[1] == "struct") { cur_size[f[2]] = f[3]; seen_struct[f[2]] = 1 }
        else if (f[1] == "symbol") cur_sym[f[2]] = 1
    }

    if (base_abi != cur_abi) {
        print "  BREAK  ABI version is now " cur_abi ", but this baseline describes ABI " base_abi
        print "         A new ABI version needs its own baseline file, not an edit to this one."
        breaks++
    }

    for (k in base_enum) {
        if (!(k in seen_enum)) fail("enumerator removed: " k " (was " base_enum[k] ")")
        else if (cur_enum[k] != base_enum[k])
            fail("enumerator renumbered: " k " was " base_enum[k] ", now " cur_enum[k])
    }
    for (k in base_off) {
        if (!(k in seen_field)) { fail("field removed: " k); continue }
        if (cur_off[k] != base_off[k])
            fail("field moved: " k " was at offset " base_off[k] ", now " cur_off[k])
        if (cur_width[k] != base_width[k])
            fail("field width changed: " k " was " base_width[k] " bytes, now " cur_width[k])
    }
    for (k in base_size) {
        if (!(k in seen_struct)) { fail("struct removed: " k); continue }
        split(k, parts, ".")
        if (cur_size[k] == base_size[k]) continue
        if (growable[k] && cur_size[k] > base_size[k]) {
            print "  grew   " k ": " base_size[k] " -> " cur_size[k] " bytes (size-prefixed; allowed)"
            continue
        }
        fail("struct size changed: " k " was " base_size[k] " bytes, now " cur_size[k] \
             (growable[k] ? " (shrank)" : " (not size-prefixed; it may never change)"))
    }
    for (k in base_sym) if (!(k in cur_sym)) fail("exported symbol removed: " k)

    for (k in seen_enum)   if (!(k in base_enum)) added_enum++
    for (k in seen_field)  if (!(k in base_off))  { added_field++; new_field[k] = 1 }
    for (k in seen_struct) if (!(k in base_size)) added_struct++
    for (k in cur_sym)     if (!(k in base_sym))  added_sym++

    # An appended field is only legal in a struct that may grow, and only past
    # where the old struct ended.
    for (k in new_field) {
        split(k, parts, ".")
        s = parts[1]
        if (!(s in base_size)) continue        # a wholly new struct: fine
        if (!growable[s])
            fail("field added to a struct that may not grow: " k)
        else if (cur_off[k] < base_size[s])
            fail("field added inside the old extent of " s ": " k " at offset " cur_off[k] \
                 ", but " s " ended at " base_size[s])
    }

    if (breaks) {
        print ""
        print "  " breaks " ABI 1 violation(s). See docs/ffi/ABI.md."
        exit 1
    }
    n = added_enum + added_field + added_struct + added_sym
    if (n)
        printf "  %d addition(s): %d enumerator(s), %d field(s), %d struct(s), %d symbol(s)\n",
               n, added_enum, added_field, added_struct, added_sym
}
' && layout_ok=1 || layout_ok=0

if [ "$layout_ok" != 1 ]; then
    echo
    echo "ABI 1 layout check FAILED against $baseline" >&2
    exit 1
fi
echo "ABI 1 layout: ok ($(grep -c . "$baseline") frozen facts)"

# --------------------------------------------------------------------------
# 5. If an archive was named - or one is lying in target/ - check that every
#    symbol in the baseline is really in it. The header promising a function
#    that the linker cannot find is a break the C compiler never sees.
# --------------------------------------------------------------------------
if [ -z "$lib" ]; then
    for candidate in "$root/target/release/libhydra.a" "$root/target/debug/libhydra.a" \
                     "$root/target/release/hydra.lib" "$root/target/debug/hydra.lib"; do
        [ -f "$candidate" ] && { lib="$candidate"; break; }
    done
fi

if [ -z "$lib" ]; then
    echo "symbols: skipped (no libhydra archive built; pass --lib PATH or run \`make ffi\`)"
    exit 0
fi

symbols="$out/lib-symbols.txt"
defined="$out/lib-defined.txt"

# The defined names, with the platform's decoration taken off: Mach-O prefixes
# an underscore, ELF and COFF do not, and the baseline names neither. `U` is
# nm's undefined marker - a symbol the archive REFERENCES is not one it
# PROVIDES, and only the second kind can satisfy a caller.
extract_nm() {
    awk '
        $2 == "U" { next }
        { name = $NF; sub(/^_/, "", name)
          if (name ~ /^hydra_[a-z0-9_]+$/) print name }
    ' "$symbols" | LC_ALL=C sort -u > "$defined"
}

if command -v nm >/dev/null 2>&1; then
    nm -g "$lib" > "$symbols" 2>/dev/null || true
    extract_nm
elif command -v llvm-nm >/dev/null 2>&1; then
    llvm-nm -g "$lib" > "$symbols" 2>/dev/null || true
    extract_nm
elif command -v dumpbin >/dev/null 2>&1; then
    # /LINKERMEMBER:1 is the archive's own public symbol table - a few hundred
    # lines. /SYMBOLS on a 30 MB staticlib is millions, and says nothing extra
    # for this question.
    dumpbin //LINKERMEMBER:1 "$lib" > "$symbols" 2>/dev/null || true
    # Tokenised rather than parsed by column, because the layout of that
    # listing is not documented and has changed between toolsets. It cannot
    # distinguish a definition from a reference, which makes this leg slightly
    # laxer than the nm one - nothing inside libhydra calls its own exports, so
    # in practice a name here is a definition.
    tr -c 'A-Za-z0-9_' '\n' < "$symbols" \
        | grep -x 'hydra_[a-z0-9_]*' \
        | LC_ALL=C sort -u > "$defined"
else
    echo "symbols: skipped (no nm, llvm-nm or dumpbin on PATH)"
    exit 0
fi

if [ ! -s "$defined" ]; then
    echo "symbols: skipped (could not read symbols out of $(basename "$lib"))"
    exit 0
fi

missing=0
while read -r _ name; do
    grep -Fxq "$name" "$defined" || {
        echo "  BREAK  $name is declared in the header but not defined in $(basename "$lib")"
        missing=$((missing + 1))
    }
done < <(grep '^symbol ' "$baseline")

if [ "$missing" -gt 0 ]; then
    echo
    echo "$missing symbol(s) missing from $lib" >&2
    exit 1
fi
echo "symbols: ok ($(grep -c '^symbol ' "$baseline") exported functions present in $(basename "$lib"))"
