//! A rate-shapeable HTTP/1.1 origin for end-to-end measurement.
//!
//! Real sockets, real `Range` handling, real `206 Partial Content` — but with a
//! programmable per-source rate cap and failure injection, so the adversarial
//! scenarios of the simulator (`throttle_midway`, `mirror_failure`) can be
//! reproduced over an actual transport rather than asserted.
//!
//! Serving generated bytes rather than a file keeps the origin from being the
//! bottleneck and keeps its own memory constant.

use crate::{Connector, Target};
use std::collections::HashMap;
use std::future::Future;
use std::io;
use std::pin::Pin;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use tokio::io::{AsyncReadExt, AsyncWriteExt, DuplexStream};

/// Deterministic pseudo-random content, so any byte can be generated (and
/// verified) from its offset alone without storing the object.
#[inline]
pub fn byte_at(off: u64) -> u8 {
    let mut x = off.wrapping_mul(0x9E37_79B9_7F4A_7C15);
    x ^= x >> 29;
    x = x.wrapping_mul(0xBF58_476D_1CE4_E5B9);
    x ^= x >> 32;
    (x & 0xFF) as u8
}

pub fn fill(buf: &mut [u8], start: u64) {
    for (i, b) in buf.iter_mut().enumerate() {
        *b = byte_at(start + i as u64);
    }
}

#[derive(Clone)]
pub struct OriginControl {
    /// Aggregate bytes/s this origin serves across all its active connections.
    pub rate: Arc<AtomicU64>,
    /// Shared token-bucket cursor: the absolute time by which the origin has
    /// already committed to having sent everything granted so far.
    paced_until: Arc<Mutex<Option<tokio::time::Instant>>>,
    /// When true, accept connections but send nothing (models a black-holing mirror).
    pub blackhole: Arc<AtomicBool>,
    /// When true, answer every request with 503 + Retry-After.
    pub overloaded: Arc<AtomicBool>,
    /// Advertise and honour ranges.
    pub ranges: Arc<AtomicBool>,
    /// Advertise a Content-Length larger than the body actually sent, then close.
    /// Models a truncating origin, which a client must not accept as complete.
    pub lie_length: Arc<AtomicBool>,
    /// Reply 301 to this path instead of serving (0 = disabled).
    pub redirect_to: Arc<Mutex<Option<String>>>,
    /// Frame the body as `Transfer-Encoding: chunked` in pieces of this many
    /// bytes (0 = disabled, send a plain body).
    ///
    /// Legal with 206 per RFC 9112 and what jsDelivr actually does. Exercising
    /// it in-process is the only way to measure the framing path's cost without
    /// a socket, and the piece size is the variable that decides that cost.
    pub chunked: Arc<AtomicU64>,
    /// Serve more than one request per connection, answering
    /// `Connection: keep-alive`.
    ///
    /// Off by default so every existing test keeps the transport it was written
    /// against. Turning it on is what makes the client's connection reuse
    /// observable at all: while the origin answers `Connection: close`, a correct
    /// client MUST NOT pool the socket, so the pool stays empty and a reuse test
    /// would pass by doing nothing.
    pub keep_alive: Arc<AtomicBool>,
    /// Silently close a keep-alive connection after it has answered this many
    /// requests (0 = never).
    ///
    /// Models what every real server does and what no in-process test did: a
    /// socket the client has finished with, and is holding for reuse, is closed by
    /// the SERVER on the server's own terms. Servers bound keep-alive both by idle
    /// time (every CDN) and by request count (nginx `keepalive_requests`), and
    /// either way the close is silent — a FIN, not a `Connection: close` header on
    /// the previous response — so a pooled stream stays indistinguishable from a
    /// healthy one until the next request's first read returns zero.
    ///
    /// Counted in requests rather than in idle milliseconds because that is the
    /// form this transport can actually be made to hit: it wakes on every arrival,
    /// so a pooled socket here is reused within microseconds and no realistic idle
    /// window would ever expire.
    pub close_after_requests: Arc<AtomicU64>,
    /// Cut every Nth response off half-way through its body (0 = never).
    ///
    /// `lie_length` models an origin that ALWAYS truncates, which a client must
    /// refuse outright. This models the far commoner one that truncates
    /// occasionally — a CDN node recycled mid-response, a load balancer dropping
    /// a connection — where the correct behaviour is not to fail but to re-request
    /// the remainder promptly.
    pub truncate_every: Arc<AtomicU64>,
    /// Requests this origin has answered, across every connection.
    ///
    /// With `keep_alive` on, comparing this against `connections` is the direct
    /// measure of reuse: `requests > connections` can only happen if the client
    /// really did send a second request down a socket it had already used.
    pub requests: Arc<AtomicU64>,
    /// Connections this origin has accepted.
    pub connections: Arc<AtomicU64>,
    /// Total payload bytes this origin has actually put on the wire, across every
    /// connection it has served.
    ///
    /// This is the measurement that distinguishes a client which preempts ranges
    /// for free from one that merely believes it does. A scheduler can report a
    /// byte-exact file and a plausible request count while having pulled parts of
    /// the object two or three times — the duplicate traffic is invisible from
    /// the client side, because the second copy of a span is written over the
    /// first and the file is correct either way. Only the server can see it. A
    /// transfer with no wasted work satisfies `served == object size`.
    pub served: Arc<AtomicU64>,
}

impl OriginControl {
    /// Reserve `n` bytes of the origin's aggregate budget and return the time at
    /// which they may be sent. Serialises all connections of one origin against
    /// a single moving cursor, so N connections share `rate`, they do not each
    /// get it.
    fn reserve(&self, n: u64) -> tokio::time::Instant {
        let rate = self.rate.load(Ordering::Relaxed).max(1);
        let dur = tokio::time::Duration::from_secs_f64(n as f64 / rate as f64);
        let now = tokio::time::Instant::now();
        let mut g = self.paced_until.lock().unwrap();
        let base = match *g {
            Some(t) if t > now => t,
            _ => now,
        };
        let next = base + dur;
        *g = Some(next);
        base
    }

    pub fn new(rate: u64) -> Self {
        OriginControl {
            rate: Arc::new(AtomicU64::new(rate)),
            paced_until: Arc::new(Mutex::new(None)),
            blackhole: Arc::new(AtomicBool::new(false)),
            overloaded: Arc::new(AtomicBool::new(false)),
            ranges: Arc::new(AtomicBool::new(true)),
            lie_length: Arc::new(AtomicBool::new(false)),
            redirect_to: Arc::new(Mutex::new(None)),
            chunked: Arc::new(AtomicU64::new(0)),
            keep_alive: Arc::new(AtomicBool::new(false)),
            close_after_requests: Arc::new(AtomicU64::new(0)),
            truncate_every: Arc::new(AtomicU64::new(0)),
            requests: Arc::new(AtomicU64::new(0)),
            connections: Arc::new(AtomicU64::new(0)),
            served: Arc::new(AtomicU64::new(0)),
        }
    }
}

/// A set of in-process origins addressed by port number.
///
/// The sandbox this was developed in forbids `bind()` on any address, so the
/// hermetic tests cannot use loopback TCP. Rather than weaken the test, the
/// transport was made generic over a `Connector` (see `lib.rs`) and the origin
/// serves over `tokio::io::duplex` instead: the same async byte stream, the same
/// HTTP/1.1 parsing on both sides, the same rate shaping and failure injection,
/// with the kernel socket replaced by an in-memory pipe. The real-network path
/// is exercised separately by `TcpConnector` against a live host.
#[derive(Clone, Default)]
pub struct OriginSet {
    inner: Arc<Mutex<HashMap<u16, (u64, OriginControl)>>>,
    next: Arc<AtomicU64>,
}

impl OriginSet {
    pub fn new() -> Self {
        OriginSet {
            inner: Arc::new(Mutex::new(HashMap::new())),
            next: Arc::new(AtomicU64::new(9000)),
        }
    }

    /// Register an origin serving a synthetic object of `size` bytes at `rate`
    /// bytes/s. Returns its port and control handle.
    /// Spawn an origin that parses `Range` and then ignores it, always replying
    /// `200 OK` with the whole object. Models the real servers that do this.
    pub fn spawn_ignoring_ranges(&self, size: u64, rate: u64) -> (u16, OriginControl) {
        let (port, ctl) = self.spawn(size, rate);
        ctl.ranges.store(false, Ordering::Relaxed);
        (port, ctl)
    }

    /// An origin that advertises a full Content-Length and then closes halfway.
    pub fn spawn_truncating(&self, size: u64, rate: u64) -> (u16, OriginControl) {
        let (port, ctl) = self.spawn(size, rate);
        ctl.lie_length.store(true, Ordering::Relaxed);
        (port, ctl)
    }

    /// An origin that always answers 503 with `Retry-After: 2`.
    pub fn spawn_overloaded(&self, size: u64, rate: u64) -> (u16, OriginControl) {
        let (port, ctl) = self.spawn(size, rate);
        ctl.overloaded.store(true, Ordering::Relaxed);
        (port, ctl)
    }

    /// An origin that 301-redirects every request to `loc`.
    pub fn spawn_redirecting(&self, size: u64, rate: u64, loc: &str) -> (u16, OriginControl) {
        let (port, ctl) = self.spawn(size, rate);
        *ctl.redirect_to.lock().unwrap() = Some(loc.to_string());
        (port, ctl)
    }

    pub fn spawn(&self, size: u64, rate: u64) -> (u16, OriginControl) {
        let port = self.next.fetch_add(1, Ordering::Relaxed) as u16;
        let ctl = OriginControl::new(rate);
        self.inner.lock().unwrap().insert(port, (size, ctl.clone()));
        (port, ctl)
    }
}

impl Connector for OriginSet {
    type Stream = DuplexStream;

    fn connect<'a>(
        &'a self,
        t: &'a Target,
    ) -> Pin<Box<dyn Future<Output = io::Result<DuplexStream>> + Send + 'a>> {
        let entry = self.inner.lock().unwrap().get(&t.port).cloned();
        Box::pin(async move {
            let Some((size, ctl)) = entry else {
                return Err(io::Error::new(
                    io::ErrorKind::ConnectionRefused,
                    "no such origin",
                ));
            };
            // 64 KiB pipe: bounded, so a slow reader back-pressures the origin
            // exactly as a TCP receive window would.
            let (client, mut server) = tokio::io::duplex(64 * 1024);
            ctl.connections.fetch_add(1, Ordering::Relaxed);
            tokio::spawn(async move {
                let _ = serve(&mut server, size, ctl).await;
            });
            Ok(client)
        })
    }
}

/// Write `<hex>\r\n` into `out`, returning the byte count. No allocation.
fn write_hex_line(out: &mut [u8; 20], mut v: usize) -> usize {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut tmp = [0u8; 16];
    let mut i = tmp.len();
    if v == 0 {
        i -= 1;
        tmp[i] = b'0';
    }
    while v > 0 {
        i -= 1;
        tmp[i] = HEX[v & 0xf];
        v >>= 4;
    }
    let n = tmp.len() - i;
    out[..n].copy_from_slice(&tmp[i..]);
    out[n] = b'\r';
    out[n + 1] = b'\n';
    n + 2
}

/// Answer requests on one connection until the peer goes away.
///
/// With `keep_alive` off this serves exactly one request and returns, which is
/// the behaviour every pre-existing test was written against. With it on, the
/// loop is what lets a client's connection reuse be observed: a second request
/// arriving on the same socket can only mean the client pooled it.
async fn serve<S>(sock: &mut S, size: u64, ctl: OriginControl) -> std::io::Result<()>
where
    S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    let mut answered = 0u64;
    loop {
        let more = serve_one(sock, size, &ctl).await?;
        if !more {
            return Ok(());
        }
        answered += 1;
        let budget = ctl.close_after_requests.load(Ordering::Relaxed);
        if budget > 0 && answered >= budget {
            half_close(sock).await?;
            return Ok(());
        }
    }
}

/// Close the write half and keep reading, the way a TCP peer that has sent FIN
/// does: the client's next request still writes successfully into a socket whose
/// reply will never come, and only its first READ reveals the close.
///
/// Dropping the stream instead would fail the client's WRITE, which is the easy
/// half of the problem and the half a client already has to handle to connect at
/// all. The silent half is what strands a pooled connection.
async fn half_close<S>(sock: &mut S) -> std::io::Result<()>
where
    S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    sock.shutdown().await?;
    let mut drain = [0u8; 4096];
    while sock.read(&mut drain).await? > 0 {}
    Ok(())
}

/// Answer one request. Returns whether the connection may carry another.
async fn serve_one<S>(sock: &mut S, size: u64, ctl: &OriginControl) -> std::io::Result<bool>
where
    S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    let keep_alive = ctl.keep_alive.load(Ordering::Relaxed);
    let mut req = Vec::new();
    let mut buf = [0u8; 4096];
    loop {
        let n = sock.read(&mut buf).await?;
        if n == 0 {
            return Ok(false);
        }
        req.extend_from_slice(&buf[..n]);
        if req.windows(4).any(|w| w == b"\r\n\r\n") {
            break;
        }
    }
    // This request's sequence number, taken at the increment. Reading the counter
    // later instead would be a race: with n ranges in flight, every one of them
    // is counted before any of their bodies start streaming, so all n would read
    // the same value and a rule like "every third response" would fire n times or
    // not at all.
    let seq = ctl.requests.fetch_add(1, Ordering::Relaxed) + 1;
    let text = String::from_utf8_lossy(&req).to_string();
    let is_head = text.starts_with("HEAD");
    let ranges_ok = ctl.ranges.load(Ordering::Relaxed);

    // What this origin tells the client about the socket's future. A client that
    // pools a connection whose response said `close` is broken; a client that
    // fails to pool one that said `keep-alive` merely leaves performance behind.
    let conn_hdr = if keep_alive {
        "Connection: keep-alive\r\n"
    } else {
        "Connection: close\r\n"
    };

    // Clone out of the lock BEFORE awaiting: a std MutexGuard is not Send, so
    // holding it across an await makes the whole future non-Send.
    let redirect = ctl.redirect_to.lock().unwrap().clone();
    if let Some(loc) = redirect {
        let resp = format!(
            "HTTP/1.1 301 Moved Permanently\r\nLocation: {loc}\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
        );
        sock.write_all(resp.as_bytes()).await?;
        return Ok(false);
    }
    if ctl.overloaded.load(Ordering::Relaxed) {
        let resp = "HTTP/1.1 503 Service Unavailable\r\nRetry-After: 2\r\nContent-Length: 0\r\nConnection: close\r\n\r\n";
        sock.write_all(resp.as_bytes()).await?;
        return Ok(false);
    }

    // parse Range: bytes=lo-hi
    let mut lo = 0u64;
    let mut hi = size;
    let mut partial = false;
    if ranges_ok {
        for line in text.lines() {
            let l = line.to_ascii_lowercase();
            if let Some(v) = l.strip_prefix("range:") {
                if let Some(spec) = v.trim().strip_prefix("bytes=") {
                    let (a, b) = spec.split_once('-').unwrap_or((spec, ""));
                    // A server with ranges disabled parses the header and then
                    // IGNORES it, replying 200 with the whole object. That is the
                    // hostile case a client must detect: the bytes are valid, but
                    // they belong at offset 0, not at the requested `lo`.
                    if ranges_ok {
                        lo = a.trim().parse().unwrap_or(0);
                        hi = b
                            .trim()
                            .parse::<u64>()
                            .map(|v| v + 1)
                            .unwrap_or(size)
                            .min(size);
                        partial = true;
                    }
                }
            }
        }
    }
    let len = hi.saturating_sub(lo);

    // A chunked framing overrides Content-Length: the two are mutually exclusive
    // (RFC 9112 §6.1), and a response carrying both is exactly the ambiguity a
    // client must not have to resolve.
    let chunk_sz = ctl.chunked.load(Ordering::Relaxed) as usize;
    let head = if chunk_sz > 0 {
        format!(
            "HTTP/1.1 {}\r\nTransfer-Encoding: chunked\r\n{}\
             Accept-Ranges: bytes\r\nETag: \"synthetic-{size}\"\r\n{conn_hdr}\r\n",
            if partial {
                "206 Partial Content"
            } else {
                "200 OK"
            },
            if partial {
                format!(
                    "Content-Range: bytes {}-{}/{}\r\n",
                    lo,
                    hi.saturating_sub(1),
                    size
                )
            } else {
                String::new()
            }
        )
    } else if partial {
        format!(
            "HTTP/1.1 206 Partial Content\r\nContent-Length: {len}\r\nContent-Range: bytes {}-{}/{}\r\n\
             Accept-Ranges: bytes\r\nETag: \"synthetic-{size}\"\r\n{conn_hdr}\r\n",
            lo,
            hi.saturating_sub(1),
            size
        )
    } else {
        format!(
            "HTTP/1.1 200 OK\r\nContent-Length: {len}\r\n{}ETag: \"synthetic-{size}\"\r\n{conn_hdr}\r\n",
            if ranges_ok { "Accept-Ranges: bytes\r\n" } else { "Accept-Ranges: none\r\n" }
        )
    };
    sock.write_all(head.as_bytes()).await?;
    if is_head {
        return Ok(keep_alive);
    }
    // A truncating origin: the advertised Content-Length is honest-looking but
    // the connection closes early. A client that trusts the header and reports
    // success here delivers a short file.
    let cut_every = ctl.truncate_every.load(Ordering::Relaxed);
    let cut =
        ctl.lie_length.load(Ordering::Relaxed) || (cut_every > 0 && seq.is_multiple_of(cut_every));
    let truncate_at = if cut { Some(lo + len / 2) } else { None };

    // Stream the body under the rate cap, in 16 KiB slices with a sleep between.
    const SLICE: usize = 16 * 1024;
    let mut out = vec![0u8; SLICE];
    // Reused framing scratch, so the origin allocates nothing per chunk.
    let mut framed: Vec<u8> = Vec::with_capacity(SLICE * 2 + 64);
    let mut off = lo;
    // Token-bucket pacing shared per CONNECTION; the aggregate per-origin cap is
    // enforced by dividing the configured rate across live connections.
    while off < hi {
        if ctl.blackhole.load(Ordering::Relaxed) {
            // Hold the connection open delivering nothing: the case the stall
            // detector exists for.
            tokio::time::sleep(tokio::time::Duration::from_millis(200)).await;
            continue;
        }
        if let Some(cut) = truncate_at {
            if off >= cut {
                return Ok(false); // close mid-body
            }
        }
        let n = ((hi - off) as usize).min(SLICE);
        // Pace BEFORE writing, against a monotonic budget. Sleeping after the
        // write lets a connection deliver its first slice for free and lets a
        // rate change take effect one slice late; with several connections per
        // origin that is enough to beat the nominal cap and make a fluid-oracle
        // ratio come out below 1, which is impossible for a correct bound.
        let send_at = ctl.reserve(n as u64);
        let now = tokio::time::Instant::now();
        if send_at > now {
            tokio::time::sleep_until(send_at).await;
        }
        fill(&mut out[..n], off);
        if chunk_sz > 0 {
            // Frame each slice into chunk_sz pieces, assembled in a REUSED
            // buffer and written once.
            //
            // The obvious spelling — `format!("{take:x}\r\n")` per chunk — makes
            // this harness allocate once per chunk. That matters because the
            // allocation profiler this origin feeds counts process-wide, so the
            // origin's own churn is indistinguishable from the client decoder's
            // and would be reported as the client's cost. Measured before this
            // change: ~1027 allocations per MiB at 1 KiB chunks, essentially all
            // of them this `format!`.
            framed.clear();
            let mut w = 0usize;
            let mut hdr = [0u8; 20];
            while w < n {
                let take = chunk_sz.min(n - w);
                let hl = write_hex_line(&mut hdr, take);
                framed.extend_from_slice(&hdr[..hl]);
                framed.extend_from_slice(&out[w..w + take]);
                framed.extend_from_slice(b"\r\n");
                w += take;
            }
            sock.write_all(&framed).await?;
        } else {
            sock.write_all(&out[..n]).await?;
        }
        // Count PAYLOAD bytes, framing excluded: the question this answers is how
        // many times each byte of the object was sent, which chunk headers would
        // distort.
        ctl.served.fetch_add(n as u64, Ordering::Relaxed);
        off += n as u64;
    }
    if chunk_sz > 0 {
        sock.write_all(b"0\r\n\r\n").await?;
    }
    Ok(keep_alive)
}
