// Copyright (C) 2026 Javad Rajabzadeh
// SPDX-License-Identifier: MIT OR Apache-2.0

//! The Netscape `cookies.txt` interchange format.
//!
//! Seven tab-separated fields per line, the format every browser extension and
//! every other downloader already reads and writes:
//!
//! ```text
//! domain  include_subdomains  path  secure  expiry  name  value
//! ```
//!
//! `domain` carries a `#HttpOnly_` prefix when the cookie is `HttpOnly`, which
//! is curl's convention and is what makes a jar round-trip through curl, wget
//! and the browser extensions without losing the flag. A `expiry` of `0` is a
//! session cookie.
//!
//! Parsing is lenient about what it reads and strict about what it writes: a
//! line with the wrong field count, an unparsable expiry, or a name that is
//! empty is skipped rather than failing the load, because these files are
//! commonly hand-edited and one bad line should not cost the user the other
//! forty. A value containing a tab or a newline is refused on WRITE — it would
//! produce a file that reads back as something else.

use super::{canonical_host, Cookie, CookieJar};

/// The header every writer puts at the top, and which some readers require.
const BANNER: &str = "# Netscape HTTP Cookie File\n\
                      # https://curl.se/docs/http-cookies.html\n\
                      # This file was generated by hydra. Edit at your own risk.\n\n";

const HTTP_ONLY: &str = "#HttpOnly_";

/// Read a `cookies.txt` body into a jar.
///
/// Returns the jar and the number of lines that were skipped as unreadable, so
/// a caller can tell "the file held nothing for this host" from "the file is
/// not a cookie jar" and say so.
pub fn parse(text: &str) -> (CookieJar, usize) {
    let mut jar = CookieJar::new();
    let mut skipped = 0;
    for line in text.lines() {
        let raw = line.trim_end_matches(['\r', '\n']);
        if raw.trim().is_empty() {
            continue;
        }
        // A comment, unless it is the HttpOnly marker, which is a comment only
        // to readers that do not know it.
        if raw.starts_with('#') && !raw.starts_with(HTTP_ONLY) {
            continue;
        }
        match parse_line(raw) {
            Some(c) => jar.insert(c),
            None => skipped += 1,
        }
    }
    (jar, skipped)
}

fn parse_line(raw: &str) -> Option<Cookie> {
    let http_only = raw.starts_with(HTTP_ONLY);
    let rest = raw.strip_prefix(HTTP_ONLY).unwrap_or(raw);
    let f: Vec<&str> = rest.split('\t').collect();
    // Seven fields, or six from a writer that omitted an empty trailing value.
    if f.len() < 6 || f.len() > 7 {
        return None;
    }
    let domain_field = f[0];
    let domain = canonical_host(domain_field);
    if domain.is_empty() {
        return None;
    }
    let name = f[5].trim();
    if name.is_empty() {
        return None;
    }
    let expiry: i64 = f[4].trim().parse().ok()?;
    Some(Cookie {
        name: name.to_string(),
        value: f.get(6).copied().unwrap_or("").to_string(),
        domain,
        // The column says so, and a leading dot says so in files written before
        // the column was trusted. Either is enough.
        host_only: !(f[1].trim().eq_ignore_ascii_case("TRUE") || domain_field.starts_with('.')),
        path: if f[2].starts_with('/') {
            f[2].to_string()
        } else {
            "/".to_string()
        },
        secure: f[3].trim().eq_ignore_ascii_case("TRUE"),
        http_only,
        expires: (expiry > 0).then_some(expiry as u64),
    })
}

/// Render a jar as a `cookies.txt` body.
///
/// Session cookies are written only when `keep_session` is set — wget's
/// `--keep-session-cookies`, and the reason it exists: a session cookie is the
/// interesting one to carry to the next run, and also the one a browser would
/// have dropped, so persisting it is a choice the user makes rather than a
/// default.
///
/// Cookies already expired at `now` are never written, and neither is one whose
/// name or value contains a tab or a newline: the format has no escape for
/// either, so writing it would produce a file that parses back as a different
/// cookie.
pub fn render(jar: &CookieJar, keep_session: bool, now: u64) -> String {
    let mut out = String::from(BANNER);
    for c in jar.iter() {
        match c.expires {
            Some(e) if e <= now => continue,
            None if !keep_session => continue,
            _ => {}
        }
        if [c.name.as_str(), c.value.as_str()]
            .iter()
            .any(|s| s.contains(['\t', '\n', '\r']))
        {
            continue;
        }
        if c.http_only {
            out.push_str(HTTP_ONLY);
        }
        let dotted = if c.host_only {
            c.domain.clone()
        } else {
            format!(".{}", c.domain)
        };
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            dotted,
            if c.host_only { "FALSE" } else { "TRUE" },
            c.path,
            if c.secure { "TRUE" } else { "FALSE" },
            c.expires.unwrap_or(0),
            c.name,
            c.value,
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "# Netscape HTTP Cookie File\n\
        .example.org\tTRUE\t/\tFALSE\t2000000000\tsession\tabc\n\
        www.example.org\tFALSE\t/files\tTRUE\t0\tcsrf\tdef\n\
        #HttpOnly_.example.org\tTRUE\t/\tTRUE\t2000000000\tsid\txyz\n";

    #[test]
    fn reads_domain_scope_secure_and_http_only_columns() {
        let (jar, skipped) = parse(SAMPLE);
        assert_eq!(skipped, 0);
        let c: Vec<&Cookie> = jar.iter().collect();
        assert_eq!(c.len(), 3);

        assert_eq!(c[0].domain, "example.org");
        assert!(!c[0].host_only);
        assert_eq!(c[0].expires, Some(2_000_000_000));

        assert_eq!(c[1].domain, "www.example.org");
        assert!(c[1].host_only);
        assert_eq!(c[1].path, "/files");
        assert!(c[1].secure);
        assert!(c[1].is_session());

        assert!(c[2].http_only);
    }

    #[test]
    fn skips_unreadable_lines_without_losing_the_good_ones() {
        let text = "example.org\tTRUE\t/\tFALSE\tnot-a-number\ta\t1\n\
                    three\tfields\tonly\n\
                    \n\
                    # a comment\n\
                    example.org\tTRUE\t/\tFALSE\t0\tgood\t1\n";
        let (jar, skipped) = parse(text);
        assert_eq!(skipped, 2);
        assert_eq!(jar.len(), 1);
        assert_eq!(jar.iter().next().unwrap().name, "good");
    }

    #[test]
    fn round_trips_through_render_and_parse() {
        let (jar, _) = parse(SAMPLE);
        let (back, skipped) = parse(&render(&jar, true, 0));
        assert_eq!(skipped, 0);
        assert_eq!(jar, back);
    }

    #[test]
    fn render_drops_session_cookies_unless_asked_and_always_drops_expired() {
        let (jar, _) = parse(SAMPLE);
        let without = render(&jar, false, 0);
        assert!(!without.contains("csrf"));
        assert!(without.contains("session"));

        let expired = render(&jar, true, 2_000_000_001);
        assert!(!expired.contains("session"));
        assert!(expired.contains("csrf"));
    }

    #[test]
    fn render_refuses_a_value_the_format_cannot_escape() {
        let mut jar = CookieJar::new();
        jar.insert(Cookie::new("ok", "fine", "example.org"));
        jar.insert(Cookie::new("bad", "a\tb", "example.org"));
        jar.insert(Cookie::new("worse", "a\nexample.org\tTRUE", "example.org"));
        let (back, skipped) = parse(&render(&jar, true, 0));
        assert_eq!(skipped, 0);
        assert_eq!(back.len(), 1);
        assert_eq!(back.iter().next().unwrap().name, "ok");
    }

    #[test]
    fn a_leading_dot_alone_marks_a_domain_cookie() {
        let (jar, _) = parse(".example.org\tFALSE\t/\tFALSE\t0\ta\t1\n");
        assert!(!jar.iter().next().unwrap().host_only);
    }
}
